/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.explore.explorecassandra.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Course extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1979495368378355734L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Course\",\"namespace\":\"com.explore.explorecassandra.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\",\"doc\":\"Id of the course\"},{\"name\":\"name\",\"type\":\"string\",\"doc\":\"Name of the course\"},{\"name\":\"author\",\"type\":\"string\",\"doc\":\"Author of course\"}],\"version\":\"1\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Course> ENCODER =
      new BinaryMessageEncoder<Course>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Course> DECODER =
      new BinaryMessageDecoder<Course>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Course> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Course> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Course>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Course to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Course from a ByteBuffer. */
  public static Course fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Id of the course */
  @Deprecated public java.lang.CharSequence id;
  /** Name of the course */
  @Deprecated public java.lang.CharSequence name;
  /** Author of course */
  @Deprecated public java.lang.CharSequence author;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Course() {}

  /**
   * All-args constructor.
   * @param id Id of the course
   * @param name Name of the course
   * @param author Author of course
   */
  public Course(java.lang.CharSequence id, java.lang.CharSequence name, java.lang.CharSequence author) {
    this.id = id;
    this.name = name;
    this.author = author;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return author;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: author = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return Id of the course
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * Id of the course
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return Name of the course
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * Name of the course
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'author' field.
   * @return Author of course
   */
  public java.lang.CharSequence getAuthor() {
    return author;
  }

  /**
   * Sets the value of the 'author' field.
   * Author of course
   * @param value the value to set.
   */
  public void setAuthor(java.lang.CharSequence value) {
    this.author = value;
  }

  /**
   * Creates a new Course RecordBuilder.
   * @return A new Course RecordBuilder
   */
  public static com.explore.explorecassandra.avro.Course.Builder newBuilder() {
    return new com.explore.explorecassandra.avro.Course.Builder();
  }

  /**
   * Creates a new Course RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Course RecordBuilder
   */
  public static com.explore.explorecassandra.avro.Course.Builder newBuilder(com.explore.explorecassandra.avro.Course.Builder other) {
    return new com.explore.explorecassandra.avro.Course.Builder(other);
  }

  /**
   * Creates a new Course RecordBuilder by copying an existing Course instance.
   * @param other The existing instance to copy.
   * @return A new Course RecordBuilder
   */
  public static com.explore.explorecassandra.avro.Course.Builder newBuilder(com.explore.explorecassandra.avro.Course other) {
    return new com.explore.explorecassandra.avro.Course.Builder(other);
  }

  /**
   * RecordBuilder for Course instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Course>
    implements org.apache.avro.data.RecordBuilder<Course> {

    /** Id of the course */
    private java.lang.CharSequence id;
    /** Name of the course */
    private java.lang.CharSequence name;
    /** Author of course */
    private java.lang.CharSequence author;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.explore.explorecassandra.avro.Course.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.author)) {
        this.author = data().deepCopy(fields()[2].schema(), other.author);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Course instance
     * @param other The existing instance to copy.
     */
    private Builder(com.explore.explorecassandra.avro.Course other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.author)) {
        this.author = data().deepCopy(fields()[2].schema(), other.author);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * Id of the course
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * Id of the course
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.explore.explorecassandra.avro.Course.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * Id of the course
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * Id of the course
      * @return This builder.
      */
    public com.explore.explorecassandra.avro.Course.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * Name of the course
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * Name of the course
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.explore.explorecassandra.avro.Course.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * Name of the course
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * Name of the course
      * @return This builder.
      */
    public com.explore.explorecassandra.avro.Course.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'author' field.
      * Author of course
      * @return The value.
      */
    public java.lang.CharSequence getAuthor() {
      return author;
    }

    /**
      * Sets the value of the 'author' field.
      * Author of course
      * @param value The value of 'author'.
      * @return This builder.
      */
    public com.explore.explorecassandra.avro.Course.Builder setAuthor(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.author = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'author' field has been set.
      * Author of course
      * @return True if the 'author' field has been set, false otherwise.
      */
    public boolean hasAuthor() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'author' field.
      * Author of course
      * @return This builder.
      */
    public com.explore.explorecassandra.avro.Course.Builder clearAuthor() {
      author = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Course build() {
      try {
        Course record = new Course();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.author = fieldSetFlags()[2] ? this.author : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Course>
    WRITER$ = (org.apache.avro.io.DatumWriter<Course>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Course>
    READER$ = (org.apache.avro.io.DatumReader<Course>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
